"""add about_me and last_seen

Revision ID: 174e594c62e3
Revises: 559945dc7b65
Create Date: 2025-11-28 23:29:06.270442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174e594c62e3'
down_revision = '559945dc7b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
