"""add user image

Revision ID: 559945dc7b65
Revises: e9ade3e674db
Create Date: 2025-11-28 22:08:58.045737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559945dc7b65'
down_revision = 'e9ade3e674db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
